set_property PACKAGE_PIN A8 [get_ports a]
set_property PACKAGE_PIN C11 [get_ports b]
set_property PACKAGE_PIN F6 [get_ports out]
set_property PACKAGE_PIN A10 [get_ports sel]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
